version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:11.9
    working_directory: ~/repo
    steps:
      - checkout

      - run: npm install

      # run tests!
      - run: npm test
